# Use Ansible Vault to encrypt the secrets.

docker_install_compose: true

madoc:
  version: 2.0 # Which semver version (e.g. 2, 2.0, 2.0.0)

  # Gateway
  gateway:
    host: https://MY_HOST.madoc.io/                   # Change this to your domain

  # Use the "install code script" to generate a pass-phrase (default: password)
  installation_code: '$2b$14$Ox8ZXjeGBR7s23VB0wqZuuYwBo13vK3oGfczzj/gQXqYM1/BUXXS6'

  # Optionally set up your SMTP server.
  mail_from_user: 'Madoc <noreply@MY_HOST.madoc.io>'
  smtp:
    user: ''
    host: ''
    port: 1025
    security: 'None'
    password: ''

  # Postgres - this can also be used to provision an external postgres. (You will need to update compose)
  shared_postgres:
    database: postgres
    port: 5432
    user: postgres
    password: postgres_password                       # Change

    enabled_users:
      - madoc_ts
      - tasks_api
      - models_api
      - config_service
      - search_api
    users:
      madoc_ts:
        user: madoc_ts
        schema: madoc_ts
        password: madoc_ts_password                   # Change
      tasks_api:
        user: tasks_api
        schema: tasks_api
        password: tasks_api_password                  # Change
      models_api:
        user: models_api
        schema: models_api
        password: models_api_password                # Change
      config_service:
        user: config_service
        schema: config_service
        password: config_service_password            # Change
      search_api:
        user: search_api
        schema: search_api
        password: search_api_password                # Change



