version: "3.9"
services:

  ## API Gateway
  gateway:
    container_name: standalone-gateway
    image: ghcr.io/digirati-co-uk/madoc-nginx:${MADOC_VERSION:-main}
    ports:
      - "8878:8080"
    links:
      - tasks-api
      - model-api
      - madoc-ts
      - config-service
      - storage-api
      - okra
      - search

  gateway-redis:
    image: redis:5-alpine

  shared-postgres:
    image: ghcr.io/digirati-co-uk/madoc-postgres:${MADOC_VERSION:-main}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_MADOC_TS_USER=madoc_ts
      - POSTGRES_MADOC_TS_SCHEMA=madoc_ts
      - POSTGRES_MADOC_TS_PASSWORD=madoc_ts_password
      - POSTGRES_TASKS_API_USER=tasks_api
      - POSTGRES_TASKS_API_SCHEMA=tasks_api
      - POSTGRES_TASKS_API_PASSWORD=tasks_api_password
      - POSTGRES_MODELS_API_USER=models_api
      - POSTGRES_MODELS_API_SCHEMA=models_api
      - POSTGRES_MODELS_API_PASSWORD=models_api_password
      - POSTGRES_CONFIG_SERVICE_USER=config_service
      - POSTGRES_CONFIG_SERVICE_SCHEMA=config_service
      - POSTGRES_CONFIG_SERVICE_PASSWORD=config_service_password
      - POSTGRES_SEARCH_API_USER=search_api
      - POSTGRES_SEARCH_API_SCHEMA=search_api
      - POSTGRES_SEARCH_API_PASSWORD=search_api_password
    volumes:
      - shared_postgres_data:/var/lib/postgresql/data:Z

  ## Services.

  madoc-ts:
    image: ghcr.io/digirati-co-uk/madoc-api:${MADOC_VERSION-main}
    restart: on-failure
    volumes:
      - jwt:/home/node/app/service-jwt-responses:Z
      - files:/home/node/app/files:Z
    environment:
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=madoc_ts
      - DATABASE_SCHEMA=madoc_ts
      - DATABASE_PASSWORD=madoc_ts_password
      - REDIS_HOST=gateway-redis
      - STORAGE_FILE_DIRECTORY=/home/node/app/files
      - NODE_ENV=production
      - MIGRATE=true
      - MADOC_INSTALLATION_CODE=${MADOC_INSTALLATION_CODE:-$2b$14$Ox8ZXjeGBR7s23VB0wqZuuYwBo13vK3oGfczzj/gQXqYM1/BUXXS6}
      - API_GATEWAY=http://gateway:8080
      - GATEWAY_HOST=http://localhost:8878
    links:
      - shared-postgres

  tasks-api:
    image: ghcr.io/digirati-co-uk/tasks-api:latest
    restart: on-failure
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=tasks_api
      - DATABASE_SCHEMA=tasks_api
      - DATABASE_PASSWORD=tasks_api_password
      - QUEUE_LIST=tasks-api,madoc-ts
      - REDIS_HOST=gateway-redis
    links:
      - shared-postgres
      - gateway-redis

  storage-api:
    image: ghcr.io/digirati-co-uk/storage-api:latest
    environment:
      - GATEWAY_HOST=http://localhost:8878
    volumes:
      - storage-api:/home/node/app/files:Z

  ## Docker hub services
  model-api:
    image: digirati/capture-models:latest
    restart: on-failure
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=models_api
      - DATABASE_SCHEMA=models_api
      - DATABASE_PASSWORD=models_api_password
    links:
      - shared-postgres

  config-service:
    image: digirati/madoc_config_service_django:175410fc5b7dbef4cc259686564fbedeb60c8789
    environment:
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - MIGRATE=True
      - LOAD=False
      - DJANGO_DEBUG=False
      - WAITRESS=False
      - POSTGRES_HOST=shared-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=config_service
      - POSTGRES_SCHEMA=config_service
      - POSTGRES_PASSWORD=config_service_password
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgres://postgres:postgres_password@shared-postgres:5432/postgres
    links:
      - shared-postgres

  search:
    image: digirati/madoc-search:latest
    environment:
      - BROWSABLE=False
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - MIGRATE=True
      - LOAD=False
      - DJANGO_DEBUG=False
      - DEBUG=False
      - WAITRESS=False
      - POSTGRES_HOST=shared-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=search_api
      - POSTGRES_SCHEMA=search_api
      - POSTGRES_PASSWORD=search_api_password
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgres://postgres:postgres_password@shared-postgres:5432/postgres
    links:
      - shared-postgres

  okra:
    image: digirati/okra:latest

volumes:

  # Shared resources
  jwt: {}

  # Databases
  shared_postgres_data: {}

  # Files
  files: {}
  storage-api: {}
