version: "3"
services:
  # Internal services

  gateway:
    image: ghcr.io/digirati-co-uk/madoc-nginx:${MADOC_VERSION:-2.0}
    ports:
      - "${PORTS_GATEWAY:-80}:8080"
    links:
      - tasks-api
      - model-api
      - madoc-ts
      - config-service
      - storage-api
      - okra
      - search

  gateway-redis:
    image: redis:5-alpine

  shared-postgres:
    image: ghcr.io/digirati-co-uk/madoc-postgres:${MADOC_VERSION:-2.0}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MADOC_TS_USER=${POSTGRES_MADOC_TS_USER}
      - POSTGRES_MADOC_TS_SCHEMA=${POSTGRES_MADOC_TS_SCHEMA}
      - POSTGRES_MADOC_TS_PASSWORD=${POSTGRES_MADOC_TS_PASSWORD}
      - POSTGRES_TASKS_API_USER=${POSTGRES_TASKS_API_USER}
      - POSTGRES_TASKS_API_SCHEMA=${POSTGRES_TASKS_API_SCHEMA}
      - POSTGRES_TASKS_API_PASSWORD=${POSTGRES_TASKS_API_PASSWORD}
      - POSTGRES_MODELS_API_USER=${POSTGRES_MODELS_API_USER}
      - POSTGRES_MODELS_API_SCHEMA=${POSTGRES_MODELS_API_SCHEMA}
      - POSTGRES_MODELS_API_PASSWORD=${POSTGRES_MODELS_API_PASSWORD}
      - POSTGRES_CONFIG_SERVICE_USER=${POSTGRES_CONFIG_SERVICE_USER}
      - POSTGRES_CONFIG_SERVICE_SCHEMA=${POSTGRES_CONFIG_SERVICE_SCHEMA}
      - POSTGRES_CONFIG_SERVICE_PASSWORD=${POSTGRES_CONFIG_SERVICE_PASSWORD}
      - POSTGRES_SEARCH_API_USER=${POSTGRES_SEARCH_API_USER}
      - POSTGRES_SEARCH_API_SCHEMA=${POSTGRES_SEARCH_API_SCHEMA}
      - POSTGRES_SEARCH_API_PASSWORD=${POSTGRES_SEARCH_API_PASSWORD}
    ports:
      - "${PORTS_SHARED_POSTGRES:-5432}:5432"
    volumes:
      - /opt/data/shared_postgres_data:/var/lib/postgresql/data:Z

  madoc-ts:
    image: ghcr.io/digirati-co-uk/madoc-api:${MADOC_VERSION:-2.0}
    restart: on-failure
    volumes:
      - ./var/jwt:/home/node/app/service-jwt-responses:Z
      - /opt/data/files:/home/node/app/files:Z
    environment:
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_MADOC_TS_USER}
      - DATABASE_SCHEMA=${POSTGRES_MADOC_TS_SCHEMA}
      - DATABASE_PASSWORD=${POSTGRES_MADOC_TS_PASSWORD}
      - REDIS_HOST=gateway-redis
      - API_GATEWAY=http://gateway:8080
      - GATEWAY_HOST=${GATEWAY_HOST}
      - STORAGE_FILE_DIRECTORY=/home/node/app/files
      - MADOC_INSTALLATION_CODE=${MADOC_INSTALLATION_CODE}
      - MIGRATE=true
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_USER=${MAIL_FROM_USER}
    links:
      - shared-postgres

  tasks-api:
    image: ghcr.io/digirati-co-uk/tasks-api:latest
    restart: on-failure
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_TASKS_API_USER}
      - DATABASE_SCHEMA=${POSTGRES_TASKS_API_SCHEMA}
      - DATABASE_PASSWORD=${POSTGRES_TASKS_API_PASSWORD}
      - QUEUE_LIST=${TASKS_QUEUE_LIST:-tasks-api,madoc-ts}
      - REDIS_HOST=gateway-redis
    links:
      - shared-postgres
      - gateway-redis


  storage-api:
    image: ghcr.io/digirati-co-uk/storage-api:latest
    restart: on-failure
    environment:
      - GATEWAY_HOST=${GATEWAY_HOST}
    volumes:
      - /opt/data/files/storage-api:/home/node/app/files

  model-api:
    image: digirati/capture-models:latest
    restart: on-failure
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_MODELS_API_USER}
      - DATABASE_SCHEMA=${POSTGRES_MODELS_API_SCHEMA}
      - DATABASE_PASSWORD=${POSTGRES_MODELS_API_PASSWORD}
    links:
      - shared-postgres

  config-service:
    image: digirati/madoc_config_service_django:175410fc5b7dbef4cc259686564fbedeb60c8789
    environment:
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - MIGRATE=True
      - LOAD=False
      - DJANGO_DEBUG=False
      - WAITRESS=False
      - POSTGRES_HOST=shared-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_CONFIG_SERVICE_USER}
      - POSTGRES_PASSWORD=${POSTGRES_CONFIG_SERVICE_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_CONFIG_SERVICE_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@shared-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    links:
      - shared-postgres

  search:
    image: digirati/madoc-search:latest
    environment:
      - BROWSABLE=False
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - MIGRATE=True
      - LOAD=False
      - WAITRESS=False
      - POSTGRES_HOST=shared-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_SEARCH_API_USER}
      - POSTGRES_PASSWORD=${POSTGRES_SEARCH_API_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SEARCH_API_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_SEARCH_API_USER}:${POSTGRES_SEARCH_API_PASSWORD}@shared-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    links:
      - shared-postgres

  okra:
    image: digirati/okra:latest

