version: "3"
services:

  ## API Gateway
  gateway:
    image: ghcr.io/digirati-co-uk/madoc-api-gateway:latest
    environment:
      - TYK_GW_STORAGE_HOST=gateway-redis
      - TYK_GW_SECRET=${GATEWAY_SECRET}
      - JWT_SERVICES=tasks-api,madoc-api,configuration-api,storage-api
    ports:
      - "80:8080"
    links:
      - madoc
      - gateway-redis
      - tasks-api
      - model-api
      - madoc-ts
      - config-service
      - storage-api
      - okra
      - search
    volumes:
      - ./var/certs:/openssl-certs:Z
    depends_on:
      - certs
      - gateway-redis

  ## Databases + Certs
  certs:
    image: ghcr.io/digirati-co-uk/madoc-certs:latest
    volumes:
      - ./var/certs:/openssl-certs:Z

  gateway-redis:
    image: redis:5-alpine

  shared-postgres:
    image: ghcr.io/digirati-co-uk/madoc-shared-postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MADOC_TS_USER=${POSTGRES_MADOC_TS_USER}
      - POSTGRES_MADOC_TS_SCHEMA=${POSTGRES_MADOC_TS_SCHEMA}
      - POSTGRES_MADOC_TS_PASSWORD=${POSTGRES_MADOC_TS_PASSWORD}
      - POSTGRES_TASKS_API_USER=${POSTGRES_TASKS_API_USER}
      - POSTGRES_TASKS_API_SCHEMA=${POSTGRES_TASKS_API_SCHEMA}
      - POSTGRES_TASKS_API_PASSWORD=${POSTGRES_TASKS_API_PASSWORD}
      - POSTGRES_MODELS_API_USER=${POSTGRES_MODELS_API_USER}
      - POSTGRES_MODELS_API_SCHEMA=${POSTGRES_MODELS_API_SCHEMA}
      - POSTGRES_MODELS_API_PASSWORD=${POSTGRES_MODELS_API_PASSWORD}
      - POSTGRES_CONFIG_SERVICE_USER=${POSTGRES_CONFIG_SERVICE_USER}
      - POSTGRES_CONFIG_SERVICE_SCHEMA=${POSTGRES_CONFIG_SERVICE_SCHEMA}
      - POSTGRES_CONFIG_SERVICE_PASSWORD=${POSTGRES_CONFIG_SERVICE_PASSWORD}
      - POSTGRES_SEARCH_API_USER=${POSTGRES_SEARCH_API_USER}
      - POSTGRES_SEARCH_API_SCHEMA=${POSTGRES_SEARCH_API_SCHEMA}
      - POSTGRES_SEARCH_API_PASSWORD=${POSTGRES_SEARCH_API_PASSWORD}
    volumes:
      - /opt/data/shared_postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  madoc-database:
    image: ghcr.io/digirati-co-uk/madoc-mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - /opt/data/mysql_data:/var/lib/mysql:Z


  ## Services.

  madoc:
    image: ghcr.io/digirati-co-uk/madoc-omeka:latest
    links:
      - madoc-database
    environment:
      - APP_ENV=${APP_ENV}
      - OMEKA__DATABASE_HOST=madoc-database
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__MAIN_SITE_DOMAIN=${MAIN_SITE_DOMAIN}
      - OMEKA__INTERNAL_URL=${OMEKA_INTERNAL_URL}
      - OMEKA__SMTP_HOST=email-smtp.us-east-1.amazonaws.com
      - OMEKA__SMTP_PORT=587
      - OMEKA__SMTP_SECURITY=tls
      - OMEKA__SMTP_USERNAME=${OMEKA_SMTP_UNAME}
      - OMEKA__SMTP_PASSWORD=${OMEKA_SMTP_PWORD}
    volumes:
      - /opt/data/omeka_files:/srv/omeka/files:Z
      - ./var/certs:/openssl-certs:Z

  madoc-ts:
    image: ghcr.io/digirati-co-uk/madoc-ts:latest
    restart: on-failure
    volumes:
      - ./var/certs:/openssl-certs:Z
      - ./var/jwt:/home/node/app/service-jwt-responses:Z
      - /opt/data/omeka_files:/home/node/app/omeka-files:Z
    environment:
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_MADOC_TS_USER}
      - DATABASE_SCHEMA=${POSTGRES_MADOC_TS_SCHEMA}
      - DATABASE_PASSWORD=${POSTGRES_MADOC_TS_PASSWORD}
      - OMEKA__DATABASE_HOST=madoc-database
      - OMEKA__DATABASE_NAME=${MYSQL_DATABASE}
      - OMEKA__DATABASE_USER=${MYSQL_USER}
      - OMEKA__DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - OMEKA__DATABASE_PORT=${MYSQL_PORT}
      - OMEKA__URL=http://madoc
      - REDIS_HOST=gateway-redis
      - API_GATEWAY=http://gateway:8080
      - OMEKA_FILE_DIRECTORY=/home/node/app/omeka-files
      - NODE_ENV=production
      - MIGRATE=true
      - GATEWAY_HOST=${MAIN_SITE_DOMAIN}
    links:
      - shared-postgres
      - madoc-database
      - madoc
    depends_on:
      - certs

  tasks-api:
    image: ghcr.io/digirati-co-uk/tasks-api:latest
    restart: on-failure
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_TASKS_API_USER}
      - DATABASE_SCHEMA=${POSTGRES_TASKS_API_SCHEMA}
      - DATABASE_PASSWORD=${POSTGRES_TASKS_API_PASSWORD}
      - QUEUE_LIST=${TASKS_QUEUE_LIST}
      - REDIS_HOST=gateway-redis
    links:
      - shared-postgres
      - gateway-redis

  storage-api:
    image: digirati/madoc-storage-api-beta:v2
    volumes:
      - /opt/data/omeka_files/storage-api:/home/node/app/files

  ## Docker hub services

  model-api:
    image: digirati/capture-models:latest
    restart: on-failure
    environment:
      - SERVER_PORT=3000
      - DATABASE_HOST=shared-postgres
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_USER=${POSTGRES_MODELS_API_USER}
      - DATABASE_SCHEMA=${POSTGRES_MODELS_API_SCHEMA}
      - DATABASE_PASSWORD=${POSTGRES_MODELS_API_PASSWORD}
    links:
      - shared-postgres

  config-service:
    image: digirati/madoc_config_service_django:175410fc5b7dbef4cc259686564fbedeb60c8789
    environment:
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - MIGRATE=True
      - LOAD=False
      - DJANGO_DEBUG=False
      - WAITRESS=False
      - POSTGRES_HOST=shared-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_CONFIG_SERVICE_USER}
      - POSTGRES_PASSWORD=${POSTGRES_CONFIG_SERVICE_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_CONFIG_SERVICE_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@shared-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    links:
      - shared-postgres
    volumes:
      - /opt/data/configuration/schemas:/app/configurator/schemas
      - /opt/data/configuration/defaults:/app/configurator/default_config

  search:
    image: digirati/madoc-search:latest
    environment:
      - BROWSABLE=False
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - MIGRATE=True
      - LOAD=False
      - DJANGO_DEBUG=False
      - DEBUG=False
      - WAITRESS=False
      - POSTGRES_HOST=shared-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_SEARCH_API_USER}
      - POSTGRES_PASSWORD=${POSTGRES_SEARCH_API_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SEARCH_API_SCHEMA}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@shared-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    links:
      - shared-postgres

  okra:
    image: digirati/okra:5d129c8
