name: Standalone docker compose
on: push
jobs:
  test-standalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:standalone-gateway appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/s/default/madoc
      - name: Bring stack down
        run: |
          docker-compose stop
          docker-compose down
